languageCode: en-US
defaultContentLanguage: en
baseURL: https://www.juaning.dev
title: JUANING.dev
theme: anubis
pagerSize: 10
copyright: JUANING
publishDir: docs
enableRobotsTXT: true

services:
  googleAnalytics:
    id: G-ZSRN0E5HWF
  disqus:
    shortname: juaning

params:
  title: 'JUANING'
  author: 'Juan Gómez'
  email: juanjose@ingomez.com
  #avatar:
  dateFormat: 'January 2, 2006'
  paginationSinglePost: true
  style: dark-without-switcher
  readMore: true
  readNextPosts: 5
  disableSummary: false
  rssAsSocialIcon: true

  social:
    - id: github
      name: neurox
    - id: linkedin
      url: https://www.linkedin.com/in/juaningdotdev

languages:
  en:
    languageName: 'English'
    menu:
      main:
        - identifier: home
          name: Home
          title: Homepage
          url: /
          weight: -1
        - identifier: about
          name: About
          title: About me
          url: /about/
          weight: 1
        - identifier: portfolio
          name: Portfolio
          title: Portfolio
          url: /portfolio/
          weight: 2
        - identifier: contact
          name: Contact
          title: Contact me
          url: /contact/
          weight: 3
    params:
      description: 'Fullstack Web Development | SysOps | Electronics | Videogames'
      locale: 'en-US'
    weight: 1
  es:
    languageName: 'Español'
    menu:
      main:
        - identifier: inicio
          name: Inicio
          title: Pagina de inicio
          url: /
          weight: -1
        - identifier: acerca
          name: Acerca
          title: Acerca de mí
          url: /acerca/
          weight: 1
        - identifier: portafolio
          name: Portafolio
          title: Portafolio
          url: /portafolio/
          weight: 2
        - identifier: contacto
          name: Contacto
          title: Contáctame
          url: /contacto/
          weight: 3
    params:
      description: 'Desarrollo Web Fullstack | SysOps | Electrónica | Videojuegos'
      locale: 'es-MX'
    weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

disableKinds:
  - taxonomy
  - term
  - post
